### ISSUE TITLE
Do line set elements support branching segments?

### ISSUE THREAD

**Issue by sean-maptek** [gmggroup/omf-python#115]
For example, say there are 9 vertices, then can segments be like this:
```
segments = [(0, 1), (1, 2), (3, 4), (2, 5), (5, 6)]
```

![image](https://user-images.githubusercontent.com/62370014/135965793-20a73b65-498c-4f0a-beb4-087ec37f2f9f.png)

There is no validation rule for `LineSet` that says that isn't allowed, There is no check that the same vertex index can't appear as the start index of a segment more than once.

**Comment by fwkoch** [comment]
Yep, that's totally fine, no constraints on how the segments connect the vertices together.
