### ISSUE TITLE
Add support for proper uv mapped textures to meshes.

### ISSUE THREAD

**Issue by timmclennan** [gmggroup/omf-python#14]
The use of textured meshes is becoming increasing prevalent in mining products.
Typically they are passed around using the obj format, but it would be good if mesh objects in the omf could support this style of textures.

In particular, the output from many of the common photogrammetric meshing approaches requires texturing using multiple image files.

**Comment by banesullivan** [comment]
> In particular, the output from many of the common photogrammetric meshing approaches requires texturing using multiple image files.

@fwkoch: Is this part resolved? Do you have it structured so each texture has it's own UV texture coords now?

**Comment by fwkoch** [comment]
@banesullivan - Yes I think so. Each `UVMappedTexture` has 1 image and 1 set of UV coords - https://github.com/gmggroup/omf/blob/dev/omf/texture.py#L35-L48 - and each `SurfaceElement` has a list of textures - https://github.com/gmggroup/omf/blob/dev/omf/texture.py#L54 - Together, this means you can have multiple images mapped to the same surface in different ways simultaneously.

Do you agree that resolves it?

**Comment by banesullivan** [comment]
Ah yes - that's it! This is actually really cool and something we do not currently support in PyVista... PyVista only allows rendering one texture per mesh so we'd have split the mesh up into a few parts when rendering in order to display this.

Are the number of UV coordinates validated so that they correspond to the number of nodes/points on the mesh?

**Comment by fwkoch** [comment]
Great to hear! And regarding validation - yes - https://github.com/gmggroup/omf/blob/e46ef412f0207eeef97a56f83ddd9bf41e83941a/omf/texture.py#L62-L78
