### ISSUE TITLE
Update readthedocs to point to GMSGDataExchange

### ISSUE THREAD

**Issue by fwkoch** [gmggroup/omf-python#17]
Docs are not updating anymore, should be an easy update on readthedocs - this was an oversight in the ARANZ -> GMSG org transition.

**Comment by rowanc1** [comment]
![image](https://cloud.githubusercontent.com/assets/913249/24410748/1918aa96-1391-11e7-91fa-173b3cd8ff15.png)

![image](https://cloud.githubusercontent.com/assets/913249/24410789/34fb9624-1391-11e7-87e3-7202a96740d2.png)
