### ISSUE TITLE
Specify array type with TypedArray ECAM standards

### ISSUE THREAD

**Issue by fwkoch** [gmggroup/omf-python#22]
Using 64-bit numbers takes up a lot of space and is often not necessary. It would be great to allow other types to be specified.

**Comment by fwkoch** [comment]
Numeric arrays should specify their types in the JSON. Allowed types should follow these standards: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#TypedArray_objects

**Comment by dbrookes96** [comment]
One of the downsides of the current format is that StringArray, ColorArray and DateTimeArray etc. store their values inside the JSON. This can increase the parsing time by a lot if you have say, a point cloud where each point has a string name (The PointSetElement has a StringData with a value for each point).
I suggest adding binary versions of these instead or starting with the new format, store them as separate non-binary comma-separated or new line separated files in the Zip archive.

**Comment by fwkoch** [comment]
@dbrookes96 - this is definitely a downside. Some thoughts on this:
- ColorArray - this should just be a `n x 3` `uint8` array, under the new standards, so that's solved
- DateTimeArray - I'm not sure this is really of practical use. DateTimes could easily be represented as floats (e.g. unix timestamp) or arbitrary string arrays. I guess the only value to having them as a separate type is for extra validation of the values. Maybe worth it...?
- StringArray - This I'm also not sure about. Is there a use-case for a large dataset with different Strings for every value (I guess this would be the datetimes-as-strings case)? Or is just mapped data where we are mapping from indices into strings good enough? If we do need to keep large StringArrays, then we do need a better way to represent them. I agree that's probably a binary version or newline-separated file.
