### ISSUE TITLE
Combine data and texture attributes

### ISSUE THREAD

**Issue by fwkoch** [gmggroup/omf-python#40]
On elements, `data` and `textures` are separate lists. However, the difference between what goes in these lists is a bit arbitrary, especially as we introduce more data/texture types like UV-mapped textures. These use an image (so are they textures?) but they are also tied to the geometry (so are they data?).

We propose eliminating `texture` attribute and assigning all data and texture objects on an element to `data`.

**Comment by banesullivan** [comment]
I like this! And it would simplify the solution to #35

**Comment by fwkoch** [comment]
This was not accepted since we are renaming `data` to `attributes` and `textures` make less sense under the latter.
