### ISSUE TITLE
New Element Class: Grouped / Composite element

### ISSUE THREAD

**Issue by fwkoch** [gmggroup/omf-python#50]
Some objects require multiple elements to accurately represent. This element type has metadata, a list of elements (which disallows other grouped elements), and attributes that apply on a per-element basis.

**Comment by dbrookes96** [comment]
A good use case for this is to build a combined drillhole element. i.e. grouping up a PointSetElement with subtype "collar" and a LineSetElement with subtype "borehole" into a single element. 

Maybe it could be useful to allow for grouped elements to be nested inside another grouped element, allowing the user to build up a combined tree of elements. What would be a reason to not allow this if we validate the group to be a valid tree of elements (i.e. no loops, no duplicate elements)?

**Comment by fwkoch** [comment]
@dbrookes96 - I totally agree with your comment on `drillhole element`. Very cool.

Regarding nested grouped elements, I don't see any technical blockers form a format point of view. I think the risk is added complication when implementing OMF in an application. A couple examples:

- converting OMF grouped elements to custom, application-specific objects - I doubt there will be complex logic that accounts for different levels of nesting to create different object types? I suspect things would be flattened to the component elements, and translated from there.
- visualization or user interacion - say, building menus to traverse a list of OMF elements - by allowing arbitrary nesting in the format, anything built on top of that requires arbitrary nesting.

If we explicitly limit to one level of nesting, then possibly more interesting things can be done with it since the data structures are more constrained?

Does this reasoning make sense? I'm really not sure, could be totally off base. Maybe it would be more OMF-like to allow for the general, arbitrarily nested case, but then suggest best practices?
