### ISSUE TITLE
Rename grid 'origin' to 'corner'

### ISSUE THREAD

**Issue by fwkoch** [gmggroup/omf-python#54]

**Comment by rowanc1** [comment]
This was a decision at the GMG Meeting.

**Comment by banesullivan** [comment]
-1 from me

Is there any specific motivation behind this? Are there other libraries that use the "corner" naming convention? I'm used to "origin" but haven't seen "corner" before

I'd understand aliasing `origin` with `corner` but not outright renaming it

**Comment by fwkoch** [comment]
This is a decision out of the recent GMG steering meeting on OMFv2. The "corner" naming convention is used in some mining software packages. Using "corner" instead of "origin" helps clarify two ambiguities:
1. Origin of block model vs. origin of plot - Using "corner" makes it slightly more clear that this is the "corner of the block relative to the plot origin" rather than one origin relative to another origin.
2. Reference to centroid of corner block or corner of corner block - many mining packages deal solely with centroids and users may assume "origin" is the origin centroid. "Corner" makes the distinction more explicit - this is the absolute corner, not a centroid.

**Comment by banesullivan** [comment]
Thanks, @fwkoch! Those are fair points 

Would this fully deprecate the `origin` property or switch meaning of that property?

**Comment by fwkoch** [comment]
There would no longer be an `origin` property. All spatial reference will now be relative to the `coordinate_reference_system`.

This means we could potentially alias `corner` with `origin` in the client libraries, since they have pretty much the same meaning between v1 and v2.

**Comment by fwkoch** [comment]
For implementation details - see my comment here: https://github.com/gmggroup/omf/issues/41#issuecomment-476482236

As a summary, this issue should likely be tackled at the same time as #41 since in the v1 implementation, `origin` is defined on a base class, not on the grid subclasses.
