### ISSUE TITLE
Sphinx 1.5 requires Python 3.4

### ISSUE THREAD

**Issue by ThomasMatern** [gmggroup/omf-python#6]
Sphinx 1.5 was released a few days ago, support for Python 3.3 was dropped.
All builds are now failing the Python 3.3 test with:
`Error: Sphinx requires at least Python 2.7 or 3.4 to run.`

**Comment by fwkoch** [comment]
Fixed here, by simply not testing docs on 3.3. https://github.com/aranzgeo/omf/pull/7
