### ISSUE TITLE
Enable dev documentation build

### ISSUE THREAD

**Issue by banesullivan** [gmggroup/omf-python#94]
@fwkoch can you enable ReadTheDocs to build the `dev` branch for the documentation?

![Screen Shot 2019-09-10 at 10 06 54 AM](https://user-images.githubusercontent.com/22067021/64630617-b96bcd00-d3b2-11e9-8721-0a6041b19b75.png)

**Comment by fwkoch** [comment]
https://omf.readthedocs.io/en/dev/index.html !!

**Comment by banesullivan** [comment]
Thanks! This will help me keep up with the latest changes and maybe start refactoring `omfvista`
